# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: appointment_book.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'appointment_book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ppointment_book.proto\"@\n\x18\x61ppointment_book_request\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\"h\n\x12time_slot_response\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\r\n\x05owner\x18\x04 \x01(\t\x12\x0f\n\x07patient\x18\x05 \x01(\t\"5\n\x10\x61ppointment_book\x12!\n\x04slot\x18\x01 \x03(\x0b\x32\x13.time_slot_response\"V\n\x0bupdate_slot\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x10\n\x08new_type\x18\x03 \x01(\x05\x12\x0f\n\x07patient\x18\x04 \x01(\t\"%\n\x12update_slot_result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x94\x01\n\x12\x61ppointmentService\x12\x42\n\x12GetAppointmentBook\x12\x19.appointment_book_request\x1a\x11.appointment_book\x12:\n\x15UpdateAppointmentBook\x12\x0c.update_slot\x1a\x13.update_slot_resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENT_BOOK_REQUEST']._serialized_start=26
  _globals['_APPOINTMENT_BOOK_REQUEST']._serialized_end=90
  _globals['_TIME_SLOT_RESPONSE']._serialized_start=92
  _globals['_TIME_SLOT_RESPONSE']._serialized_end=196
  _globals['_APPOINTMENT_BOOK']._serialized_start=198
  _globals['_APPOINTMENT_BOOK']._serialized_end=251
  _globals['_UPDATE_SLOT']._serialized_start=253
  _globals['_UPDATE_SLOT']._serialized_end=339
  _globals['_UPDATE_SLOT_RESULT']._serialized_start=341
  _globals['_UPDATE_SLOT_RESULT']._serialized_end=378
  _globals['_APPOINTMENTSERVICE']._serialized_start=381
  _globals['_APPOINTMENTSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
