# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpatient.proto\"-\n\x17patient_details_request\x12\x12\n\npatient_id\x18\x01 \x01(\x05\"T\n\x0fpatient_details\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05notes\x18\x03 \x01(\t\x12\x0b\n\x03\x64ob\x18\x04 \x01(\t\"m\n\x15list_patients_request\x12\x12\n\npatient_id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x19\n\x11number_of_results\x18\x04 \x01(\x05\";\n\x16list_patients_response\x12!\n\x07patient\x18\x01 \x03(\x0b\x32\x10.patient_details\"*\n\x17\x63reate_patient_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xcf\x01\n\x0ePatientService\x12;\n\rCreatePatient\x12\x10.patient_details\x1a\x18.create_patient_response\x12?\n\x11GetPatientDetails\x12\x18.patient_details_request\x1a\x10.patient_details\x12?\n\x0cListPatients\x12\x16.list_patients_request\x1a\x17.list_patients_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENT_DETAILS_REQUEST']._serialized_start=17
  _globals['_PATIENT_DETAILS_REQUEST']._serialized_end=62
  _globals['_PATIENT_DETAILS']._serialized_start=64
  _globals['_PATIENT_DETAILS']._serialized_end=148
  _globals['_LIST_PATIENTS_REQUEST']._serialized_start=150
  _globals['_LIST_PATIENTS_REQUEST']._serialized_end=259
  _globals['_LIST_PATIENTS_RESPONSE']._serialized_start=261
  _globals['_LIST_PATIENTS_RESPONSE']._serialized_end=320
  _globals['_CREATE_PATIENT_RESPONSE']._serialized_start=322
  _globals['_CREATE_PATIENT_RESPONSE']._serialized_end=364
  _globals['_PATIENTSERVICE']._serialized_start=367
  _globals['_PATIENTSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
