# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import patient_pb2 as patient__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePatient = channel.unary_unary(
                '/PatientService/CreatePatient',
                request_serializer=patient__pb2.patient_details.SerializeToString,
                response_deserializer=patient__pb2.create_patient_response.FromString,
                _registered_method=True)
        self.GetPatientDetails = channel.unary_unary(
                '/PatientService/GetPatientDetails',
                request_serializer=patient__pb2.patient_details_request.SerializeToString,
                response_deserializer=patient__pb2.patient_details.FromString,
                _registered_method=True)
        self.ListPatients = channel.unary_unary(
                '/PatientService/ListPatients',
                request_serializer=patient__pb2.list_patients_request.SerializeToString,
                response_deserializer=patient__pb2.list_patients_response.FromString,
                _registered_method=True)


class PatientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=patient__pb2.patient_details.FromString,
                    response_serializer=patient__pb2.create_patient_response.SerializeToString,
            ),
            'GetPatientDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientDetails,
                    request_deserializer=patient__pb2.patient_details_request.FromString,
                    response_serializer=patient__pb2.patient_details.SerializeToString,
            ),
            'ListPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPatients,
                    request_deserializer=patient__pb2.list_patients_request.FromString,
                    response_serializer=patient__pb2.list_patients_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PatientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PatientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientService/CreatePatient',
            patient__pb2.patient_details.SerializeToString,
            patient__pb2.create_patient_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientService/GetPatientDetails',
            patient__pb2.patient_details_request.SerializeToString,
            patient__pb2.patient_details.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientService/ListPatients',
            patient__pb2.list_patients_request.SerializeToString,
            patient__pb2.list_patients_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
