syntax = "proto3";

// Login
message login_request {
  string username = 1;
  bytes password = 2;
}

message login_result {
  bool success = 1;
  string token = 2;
}

// Check is a user exists
message user_exists_request {
  string username = 1;
}

message user_exists_response {
  bool exists = 1;
}

// Get salt
message salt_request {
  string username = 1;
}

message password_salt {
  bytes salt = 1;
}

// Register
message register_result {
  bool success = 1;
}

message register_request {
  string username = 1;
  bytes password = 2;
  bytes salt = 3;
  int32 user_type = 4;
}

// Delete user
message delete_request {
  string username = 1;
}

message delete_result {
  bool success = 1;
}

// Logout
message logout_request {
  string token = 1;
}

message logout_response {
  bool success = 1;
}

// List users
message list_users_request {
  int32 user_type = 1;
}

message user_details {
  string username = 1;
  int32 user_type = 2;
}

message list_user_response {
  repeated user_details users = 1;
}

service AuthService {
  rpc GetSalt(salt_request) returns (password_salt);
  rpc Login(login_request) returns (login_result);
  rpc CreateAccount(register_request) returns (register_result);
  rpc CheckUserExists(user_exists_request) returns (user_exists_response);
  rpc DeleteUser(delete_request) returns (delete_result);
  rpc Logout(logout_request) returns (logout_response);
  rpc ListUsers(list_users_request) returns (list_user_response);
}

