syntax = "proto3";

message patient_details_request {
  int32 patient_id = 1;
}

message patient_details {
  int32 patient_id = 1;
  string first_name = 2;
  string last_name = 3;
  string notes = 4;
  string dob = 5;
}

message list_patients_request {
  int32 patient_id = 1;
  string first_name = 2;
  string last_name = 3;
  int32 number_of_results = 4;
}

message list_patients_response {
  repeated patient_details patient = 1;
}

message create_patient_response {
  bool success = 1;
}

service PatientService {
  rpc CreatePatient(patient_details) returns (create_patient_response);
  rpc GetPatientDetails(patient_details_request) returns (patient_details);
  rpc ListPatients(list_patients_request) returns (list_patients_response);
}
